# Generated by Django 6.0.5 on 2026-05-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('breed_info', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='pets/')),
                ('description', models.CharField(max_length=255)),
                ('health', models.CharField(max_length=255)),
                ('behavior', models.CharField(max_length=255)),
                ('care', models.CharField(max_length=255)),
                ('extra', models.CharField(max_length=255)),
                ('seller', models.CharField(max_length=255)),
            ],
        ),
    ]
