# Generated by Django 6.0.5 on 2026-05-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('breed_info', models.CharField()),
                ('img', models.ImageField(upload_to='pets/')),
                ('description', models.CharField()),
                ('health', models.CharField()),
                ('behavior', models.CharField()),
                ('care', models.CharField()),
                ('extra', models.CharField()),
                ('seller', models.CharField()),
            ],
        ),
        migrations.DeleteModel(
            name='Pets',
        ),
    ]
